package main

import "fmt"

func main() {
	sum := 0
	thisFib := 1
	f := 0

	for lastFib := 0; lastFib < 4000001; lastFib = f {
		f = thisFib
		thisFib += lastFib

		if thisFib%2 == 0 {
			sum += thisFib
		}
	}
	fmt.Println(sum)
}
/*  projecteuler.net PROBLEM
    Each new term in the Fibonacci sequence is generated by 
    adding the previous two terms. By starting with 1 and 2, 
    the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose 
    values do not exceed four million, find the sum of the 
    even-valued terms.
*/